



import Sidebar from "@/common/dashboardSidebar/Sidebar";
import type { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
     title: " ShowFLIX | Dashboard",
     description: "Generated by create next app",
};

export default function DashboardLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <div className="min-h-screen md:my-2">
               <div className="flex flex-col md:flex-row">

                    <div className=" md:w-[28%] ">
                         <Sidebar />
                    </div>

                    <div className="w-full">
                    <Toaster richColors  position="top-center" ></Toaster>
                         {children}
                        
                    </div>
               </div>
          </div>
     );
}